#include <stdio.h>
#include "stm32f4xx.h"                  // Device header
#include "stm32f4xx_conf.h"
#include "tilt_detection.h"
#include "interrupt.h"

int main(){

	//------------------Configuation and Initialization----------------------------
	uint8_t temp;
	Accel_InitConfig(LIS302DL_LOWPOWERMODE_ACTIVE, // power on the mems sensor
									 LIS302DL_DATARATE_100, // Data rate at 100 Hz as specified
									 LIS302DL_X_ENABLE | LIS302DL_Y_ENABLE | LIS302DL_Z_ENABLE,  // Enable all the axes
									 LIS302DL_SENSITIVITY_2_3G, // We won't get up to 9 g's of force in this lab
									 temp); // self test?
	
	InitInterrupt();
	
	while(1){
		// interrupt
		if (EXTI_GetFlagStatus(EXTI_Line0) == SET) {
			EXTI_ClearFlag(EXTI_Line0);
			
			// sample
			int xyz[3];
			getTilt(ALPHA, xyz);
			
			printf("x: %i, y: %i, z: %i\n", xyz[0], xyz[1], xyz[2]);
			
			// logic
		}
		
/**
	*	@brief Tilt detection using STM32F407VG (Accelerometer version M8997B)
	*	
	*	- Measure tilt angles in 2 dimensions (roll around the x-axis and pitch around the y-axis)
	*	- Real time measurements with at least 100 data points per second (frequency = 100Hz, period = 0.01s)
	*	- MEMS driver for M8997B : LIS302DL (can be found under Accelerometer_Drivers)
	*/
	
	
/**
	*	@brief Sensor Calibration
	*	
	*	- Use reset button to allow user to calibrate sensor
	*/		

	
/**
	*	@brief Data Filtering
	*	
	*	- Use Kalman filter to process data
	* - Kalman state variables: q = 
	*														r = 
	*														x =
	*														k =
	*														p =
	*/		
		


/**
	*	@brief User interface
	*	
	*	- Read user input from keypad
	*	- Translate numbers to be displayed into control signals
	*	- Send signals out through 7-segment display
	*/
	
	
/**
	*	@brief Hardware Timer
	*	
	*	- Control 7-segment multiplexing operations 
	*	- Delay generated by TIM8
	*	- Use specific bus clock (RCC driver): TimerClockingFrequency / (Period x prescalar) = desired rate
	*/	
	
	}
	
	return 0;
}

/**
	*	@brief Interrupt Handler
	*	
	*	- MEMs sensor controled interrupts
	*	- Used to control:	when data is ready
	*											when 7-segment display should be updated
	*/
